[build]
  publish = "dist"  # 替换为你的构建输出目录
  functions = "functions"  # 如果有 Netlify Functions，指定目录

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  # 解决vue部署后子菜单报错，但是vitepress会冲突，保留方法以后再尝试