/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const SvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<"admin" | "antv" | "barcodesvg" | "dashboard1" | "dhtmlx" | "draggable" | "echarts" | "editor" | "enter" | "excel" | "formCreate" | "fullscreen-exit" | "fullscreen" | "guide" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "map" | "markdown" | "mindmap" | "mint" | "pdf" | "permission" | "pinyin" | "plugin-light" | "plugin" | "search" | "table" | "threejs" | "typeit" | "vcharts" | "verify" | "vtable" | "watermark">;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<"admin" | "antv" | "barcodesvg" | "dashboard1" | "dhtmlx" | "draggable" | "echarts" | "editor" | "enter" | "excel" | "formCreate" | "fullscreen-exit" | "fullscreen" | "guide" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "map" | "markdown" | "mindmap" | "mint" | "pdf" | "permission" | "pinyin" | "plugin-light" | "plugin" | "search" | "table" | "threejs" | "typeit" | "vcharts" | "verify" | "vtable" | "watermark">;
          default: string;
          required: true;
      };
  }>>, {
      name: "admin" | "antv" | "barcodesvg" | "dashboard1" | "dhtmlx" | "draggable" | "echarts" | "editor" | "enter" | "excel" | "formCreate" | "fullscreen-exit" | "fullscreen" | "guide" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "map" | "markdown" | "mindmap" | "mint" | "pdf" | "permission" | "pinyin" | "plugin-light" | "plugin" | "search" | "table" | "threejs" | "typeit" | "vcharts" | "verify" | "vtable" | "watermark";
  }>;
  export const svgNames: ["admin", "antv", "barcodesvg", "dashboard1", "dhtmlx", "draggable", "echarts", "editor", "enter", "excel", "formCreate", "fullscreen-exit", "fullscreen", "guide", "keyboard-down", "keyboard-enter", "keyboard-esc", "keyboard-up", "map", "markdown", "mindmap", "mint", "pdf", "permission", "pinyin", "plugin-light", "plugin", "search", "table", "threejs", "typeit", "vcharts", "verify", "vtable", "watermark"];
  export type SvgName = "admin" | "antv" | "barcodesvg" | "dashboard1" | "dhtmlx" | "draggable" | "echarts" | "editor" | "enter" | "excel" | "formCreate" | "fullscreen-exit" | "fullscreen" | "guide" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "map" | "markdown" | "mindmap" | "mint" | "pdf" | "permission" | "pinyin" | "plugin-light" | "plugin" | "search" | "table" | "threejs" | "typeit" | "vcharts" | "verify" | "vtable" | "watermark";
  export default SvgIcon;
}
